x = str("Hello World")
print(x)
x = int(32)
print(x)
x = float(20.5)
print(x)
x = complex(3j)
print(x)
x = list(("apple", "banana", "cherry"))
print(x)
x = tuple(("apple", "banana", "cherry"))
print(x)
x = range(6)
print(x)
x = list(range(6,12))
print(x)
x = dict(name="apple", weight=2)
print(x)
x = set(list(("apple", "banana", "cherry")))
print(x)
x = frozenset(("apple", "banana", "cherry"))
print(x)
x = bool(1) #0 for false
print(x)
x = bytes(5)
print(x)
x = bytearray(2)
print(x)
x = memoryview(x)
print(x)